name: release

on:
  pull_request:
    paths:
      - core/**
      - .github/workflows/release.yaml
      - gradle/**
      - '*.gradle'
  release:
    types:
      - created

env:
  GROOVY_SSH_VERSION: ${{ github.event.release.tag_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew sign
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - if: github.event_name == 'release'
        run: ./gradlew publish
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

  cli:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew shadowJar
      - run: java -jar cli/build/libs/gssh.jar
