name: release

on:
  pull_request:
    paths:
      - core/**
      - .github/workflows/release.yaml
      - gradle/**
      - '*.gradle'
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2

      - if: github.event_name != 'release'
        run: ./gradlew generateMetadataFileForMavenPublication generatePomFileForMavenPublication

      - if: github.event_name == 'release'
        run: ./gradlew publish
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cli:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew shadowJar
      - run: java -jar cli/build/libs/gssh.jar
